"""empty message

Revision ID: 2dc6341f5a77
Revises: ffdc0a98111c
Create Date: 2022-01-19 11:59:38.758159

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '2dc6341f5a77'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challengerId', sa.Integer(), nullable=False),
    sa.Column('recipientId', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.ForeignKeyConstraint(['challengerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipientId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completedGames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('challengerId', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=5), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('pointsAwarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challengerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('friender_id', sa.Integer(), nullable=True),
    sa.Column('friendee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friendee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friender_id'], ['users.id'], )
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('listId', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['listId'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_table('words')
    op.drop_table('lists')
    op.drop_table('friends')
    op.drop_table('completedGames')
    op.drop_table('challenges')
    # ### end Alembic commands ###
