"""empty message

Revision ID: 343da82ecb29
Revises: 2dc6341f5a77
Create Date: 2023-09-15 14:20:44.162815

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '343da82ecb29'
down_revision = '2dc6341f5a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friender_id', sa.Integer(), nullable=True),
    sa.Column('friendee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friendee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friender_id'], ['users.id'], )
    )
    op.drop_table('friends')

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friendee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friendee_id'], ['users.id'], name='friends_friendee_id_fkey'),
    sa.ForeignKeyConstraint(['friender_id'], ['users.id'], name='friends_friender_id_fkey')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###
